export const LOAD_SMURF = "LOAD_SMURF";
export const LOAD_SMURF_SUCCESS = "LOAD_SMURF_SUCCESS";
export const LOAD_SMURF_FAILURE = "LOAD_SMURF_FAILURE";

export const ADD_SMURF = "ADD_SMURF";
export const ADD_SMURF_SUCCESS = "ADD_SMURF_SUCCESS";
export const ADD_SMURF_FAILURE = "ADD_SMURF_FAILURE";

export const DELETE_SMURF = "DELETE_SMURF";
export const DELETE_SMURF_SUCCESS = "DELETE_SMURF_SUCCESS";
export const DELETE_SMURF_FAILURE = "DELETE_SMURF_FAILURE";
